name: where_am_i
description: A Flutter app that displays your location on a map based on your current region.

publish_to: 'none' # Remove this line if you're publishing the package.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.0
  http: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/  # Optional: only include if you have assets to add
